### ISSUE TITLE
[Request] Rep Items

### ISSUE THREAD

**Issue by ChrisKader** [N6REJ/AdiBags_Bears_Ultimate#10]
[Dragonflight Rep Items](https://www.wowhead.com/items?filter=166:107;10:0;0:Grants+*+reputation)

I can also do a PR if that would help.

**Comment by N6REJ** [comment]
that would be great

**Comment by N6REJ** [comment]
I have most in "turn in"

**Comment by N6REJ** [comment]
fixed in latest release
