### ISSUE TITLE
[Request] Merging of All Bears Filters

### ISSUE THREAD

**Issue by ChrisKader** [N6REJ/AdiBags_Bears_Ultimate#11]
By utilizing the plugin/module system of AdiBags, you are able to merge all your filters into a single plugin that then allows a user to select which filters they want to enable/disable and provide customized options.

![image](https://user-images.githubusercontent.com/633360/227808554-e26a8df7-825e-48b4-861a-4b53d3053a5c.png)

**Comment by N6REJ** [comment]
do you know of an example of how to do this?

**Comment by N6REJ** [comment]
After doing some investigating it would require I combine all the addons into a single unit.  I prefer not to do that.
