### ISSUE TITLE
New Category for Weapon Runes, Whetstones, etc.

### ISSUE THREAD

**Issue by Kionica** [N6REJ/AdiBags_Bears_Ultimate#14]
Hi

Would it be possible to get a category for Weapon Runes, Whetstones ,etc?

Currently Buzzing is listed under other and Howling is listed under phials for me.

**Comment by N6REJ** [comment]
Other is provided by AdiBags itself.  I"ll look into this.

**Comment by N6REJ** [comment]
released as "Enhancements" in 2023.6.10
