### ISSUE TITLE
Dreambloom Petal Not Categorized

### ISSUE THREAD

**Issue by jwaisner** [N6REJ/AdiBags_Bears_Ultimate#4]
Dreambloom Petal is not categoriezed under "tradeskill" like others such as Dragon Shard of Knowledge.

![image](https://user-images.githubusercontent.com/12568201/205545215-69d95b55-2d74-4dc6-89bd-ca8ceb3714df.png)

**Comment by N6REJ** [comment]
Tradeskill isn't ours, After doing some investigation there are over 1000 items that would fall under misc/tradeskill
I've added the following to ultimate under "Knowledge"
```
			[191784] = true, -- Dragon Shard of Knowledge
			[198137] = true, -- Esoteric Dragon Shard of Knowledge
			[200677] = true, -- Dreambloom Petal
```
as/if you find others please feel free to create a ticket.
